/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.views;

import java.awt.Color;
import presentacion.controllers.BoardController;
import presentacion.model.Modelo;

/**
 *
 * @author Andre Sarmiento
 */
public class BoardView extends javax.swing.JFrame {

    private Modelo myGame;
    private BoardController boardCtrl;

    private TestCanvas lienzo;


    private Robot robot;

    public BoardView(Modelo aThis) {
        myGame = aThis;
        boardCtrl = getBoardCtrl();

        robot = new Robot();

        lienzo = getLienzo();

        add(lienzo);

        initComponents();
        addListeners();

        this.setLocationRelativeTo(null);

    }

    public void addListeners() {
        addKeyListener(getBoardCtrl());
    }

    public Modelo getMyGame() {
        return myGame;
    }

    public BoardController getBoardCtrl() {
        if (boardCtrl == null) {
            boardCtrl = new BoardController(this);
        }
        return boardCtrl;
    }

    public TestCanvas getLienzo() {
        if (lienzo == null) {
            lienzo = new TestCanvas(this);
            lienzo.setBounds(0, 0, 800, 480);
            lienzo.setBackground(Color.white);
        }
        return lienzo;
    }
    
    

    public Robot getRobot() {
        return robot;
    }
    
 

//     public Robot setRobot(int i) {
//         
//        return robot;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(816, 518));
        setSize(new java.awt.Dimension(816, 518));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
